### ISSUE TITLE
Thief effect does not apply

### ISSUE THREAD

**Issue by MrHimera** [mortuusars/Monobank#5]
When trying to open a chest near a villager, the thief effect is not applied and the chest does not open, and errors appear in the log.
https://pastebin.com/j3jdYZ2M

**Comment by mortuusars** [comment]
This is most likely a bug with other mod. My code is only checking for the nearest theft_protected structure and it fails much later in the code I don't control. 
I see you have a mod installed that's created in MCreator, this is probably the first thing that should be checked if removing it resolves the issue.

**Comment by MrHimera** [comment]
The error was related to the "Spawn Structures" mod.
